---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  tasks:
    - name: init role without actually running it
      include_role:
        name: acme.my_new_role
        tasks_from: init

